server:
  port: 9999

spring:
  application:
    name: cloud-oauth-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    port: 6377
    host: 10.90.15.35
    password: qweEX123
management:
  endpoints:
    web:
      exposure:
        include: "*"
#logging:
#  level:
#    org.springframework: DEBUG




