server:
  port: 9998
spring:
  application:
    name: cloud-test-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    port: 6377
    host: 10.90.15.35
    password: qweEX123

custom:
  oauth2:
    client:
      # jwt的密钥
      signingKey: test_key
      resourceId: ${spring.application.name}
      # 放行的url
      ignoreUrls:
        - /oauth/**
        - /user/**

#logging:
#  level:
#    org.springframework: DEBUG