server:
  port: 9999
spring:
#  profiles:
#    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    port: 6377
    host: 0.0.0.0
    password: qweEX123
management:
  endpoints:
    web:
      exposure:
        include: "*"




